<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GVPH1DS" name="com.browserstack.suite.SuiteAddABillWithSaving" tests="1" failures="1" timestamp="10 Aug 2018 08:20:40 GMT" time="606.711" errors="0">
  <testcase name="test_01" time="606.711" classname="com.browserstack.suite.SuiteAddABillWithSaving">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [0] but found [180]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [0] but found [180]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.browserstack.suite.AppKeyWords.addABillWithSaving(AppKeyWords.java:136)
	at com.browserstack.suite.SuiteAddABillWithSaving.test_01(SuiteAddABillWithSaving.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- test_01 -->
</testsuite> <!-- com.browserstack.suite.SuiteAddABillWithSaving -->
